// Code generated by llcppg; DO NOT EDIT.

package zlib

import "github.com/goplus/lib/c"

const MAX_MEM_LEVEL = 9
const MAX_WBITS = 15

type SizeT = c.SizeT
type Byte = uint8
type UInt = c.Uint
type ULong = c.Ulong
type Bytef = Byte
type Charf = c.Char
type Intf = c.Int
type UIntf = UInt
type ULongf = ULong
type Voidpc uintptr
type Voidpf uintptr
type Voidp uintptr
type CrcT = c.Uint
